name: autoflight-generator
base: core22
version: '2.1.0'
summary: VERSATILE UAS Flight Generator - Mission Planning Tool
description: |
  A comprehensive drone/UAS flight planning and mission generation tool
  that helps users create various types of flight missions including:
  - Point-to-point navigation
  - Delivery routes
  - Security patrols
  - Mapping flights
  - Tower inspections
  - Structure scans
  
  Features:
  - Aircraft parameter integration for ArduPilot and PX4
  - Terrain-aware flight planning with elevation queries
  - Individual tool parameter control
  - Enhanced tutorial system
  - Google Satellite map integration
  - Auto-save functionality
  - KML export and QGroundControl compatibility

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  autoflight-generator:
    command: bin/launch-autoflight-generator
    desktop: usr/share/applications/autoflight-generator.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - removable-media
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu

parts:
  autoflight-generator:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    build-packages:
      - python3-dev
      - build-essential
      - libgl1-mesa-dev
      - libglib2.0-dev
      - libgirepository1.0-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libatk1.0-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - qtbase5-dev
      - qtwebengine5-dev
      - pkg-config
    stage-packages:
      - python3
      - python3-pip
      - libqt5widgets5
      - libqt5webengine5
      - libqt5webenginewidgets5
      - libqt5webchannel5
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5positioning5
      - libqt5printsupport5
      - libqt5qml5
      - libqt5quick5
      - libqt5sql5
      - libqt5svg5
      - libqt5test5
      - libqt5websockets5
      - libqt5xml5
      - qt5-gtk-platformtheme
      - qtwayland5
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - libgl1-mesa-glx
      - libglu1-mesa
      - libegl1-mesa
      - mesa-utils
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxcb-xinerama0
      - libxcb-randr0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-util1
      - ca-certificates
    override-build: |
      craftctl default
      
      # Copy application files
      cp -r Images $CRAFTCTL_PART_INSTALL/
      cp -r assets $CRAFTCTL_PART_INSTALL/
      cp -r aircraft_parameters $CRAFTCTL_PART_INSTALL/
      cp *.py $CRAFTCTL_PART_INSTALL/
      cp *.json $CRAFTCTL_PART_INSTALL/
      cp *.html $CRAFTCTL_PART_INSTALL/
      cp *.txt $CRAFTCTL_PART_INSTALL/
      
      # Create launch script
      mkdir -p $CRAFTCTL_PART_INSTALL/bin
      cat > $CRAFTCTL_PART_INSTALL/bin/launch-autoflight-generator << 'EOF'
      #!/bin/bash
      cd $SNAP
      export PYTHONPATH=$SNAP/lib/python3.10/site-packages:$PYTHONPATH
      export QT_QPA_PLATFORM_PLUGIN_PATH=$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      export QT_PLUGIN_PATH=$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      export QTWEBENGINEPROCESS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess
      
      # Enable GPU acceleration if available
      if [ -e /dev/dri ]; then
          export QT_QPA_PLATFORM=xcb
      fi
      
      # Run the application
      exec python3 $SNAP/dashboard.py "$@"
      EOF
      chmod +x $CRAFTCTL_PART_INSTALL/bin/launch-autoflight-generator

  desktop-file:
    plugin: dump
    source: snap/local/
    organize:
      autoflight-generator.desktop: usr/share/applications/autoflight-generator.desktop
      autoflight-generator.png: usr/share/pixmaps/autoflight-generator.png

layout:
  /usr/lib/x86_64-linux-gnu/qt5/plugins:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
  /usr/share/qtchooser:
    bind: $SNAP/usr/share/qtchooser
